### ISSUE TITLE
source code license

### ISSUE THREAD

**Issue by rubiojr** [jangxx/go-poclient#2]
@jangxx I'd love to use the client library in an open source project and wondering if you'd be willing to add a license to it.

Thanks!

**Comment by jangxx** [comment]
Yea sure, I added it right now. Conceptually this library is part of this other project of mine (https://github.com/jangxx/SchubsiGo), which was already released under the MIT license for years, so I guess I just forgot to add it.

**Comment by rubiojr** [comment]
Thank you! nice client BTW :).
